---
pool: Default

trigger: none

pr:
  - develop
# link to github repo
resources:
  repositories:
    - repository: resuabePublicAssets
      type: github
      name: Rk-Yadav7899/AzureDevOpsTemplates  
      refs: 'refs/heads/main'    

steps:
  - template: templates/dotnetcore-build.yaml@resuabePublicAssets
    parameters:
      mainproect: 'src/Presentation/Nop.Web/Nop.Web.csproj'
      testproject: 'src/Test/Nop.Tests/Nop.Test.Csproj'
      runTests: false